Repository Abagatinho/visual-curriculum, pull requests merged in 2022-06, with the labels that each got.

#5 Scrapying script
  public/university/UFPE/cienciaDaComputacao.json
  public/university/UFPE/engenhariaDaComputacao.json
  public/university/UFPE/sistemasDeInformacao.json
  requirements.txt
  scrapy.py
Labels: enhancement

#8 Update eletivas
  db.json
  src/App.tsx
  src/components/DisciplineBox/index.css
  src/components/DisciplineBox/index.tsx
  src/models/Curriculum.ts
  src/pages/Home/index.tsx
Labels: enhancement

#9 Bug/scrapper
  .gitignore
  scrapy.py
  src/models/Curriculum.ts
  src/pages/Home/index.tsx
  src/utils/disciplinesHashMap.ts
  src/utils/requestDisciplines.ts
  src/utils/setAcademicHours.ts
Labels: bug, enhancement

#14 Style/renewab
  .env.example
  .github/DetailComponent.png
  .github/mainPage.png
  .github/routes.png
  src/assets/img/Logotipo-CIn.svg
  src/assets/img/abagatinho.svg
  src/components/DisciplineBox/index.tsx
  src/components/Footer/index.tsx
  src/components/NextSteps/index.tsx
  src/components/StatsContainer/index.tsx
  src/pages/Curriculum/index.tsx
  src/pages/Home/index.tsx
Labels: documentation, enhancement, good first issue

#15 Resolve bugs and update the visual - Merge develop to main
  .env.example
  .github/DetailComponent.png
  .github/mainPage.png
  .github/routes.png
  README.md
  src/assets/img/Logotipo-CIn.svg
  src/assets/img/abagatinho.svg
  src/components/DisciplineBox/index.tsx
  src/components/Footer/index.tsx
  src/components/NextSteps/index.tsx
  src/components/StatsContainer/index.tsx
  src/pages/Curriculum/index.tsx
  src/pages/Home/index.tsx
Labels: documentation, enhancement, good first issue, help wanted
